import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Kinetic Precision Design System
        "on-surface-variant": "#434750",
        "on-secondary-fixed": "#002111",
        "secondary-fixed-dim": "#59de9b",
        "secondary-fixed": "#78fbb6",
        "background": "#fbf9f8",
        "on-tertiary-container": "#c39100",
        "primary-container": "#002f6c",
        "on-tertiary-fixed": "#261a00",
        secondary: "#006d43",
        "on-secondary-fixed-variant": "#005232",
        "surface-container-high": "#eae8e7",
        "outline-variant": "#c4c6d2",
        "on-primary-container": "#7999dc",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#5c4300",
        primary: "#001b44",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#fbbc00",
        surface: "#fbf9f8",
        outline: "#747781",
        "on-primary-fixed-variant": "#224583",
        "surface-tint": "#3c5d9c",
        "inverse-surface": "#303030",
        "on-surface": "#1b1c1c",
        "primary-fixed-dim": "#aec6ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#aec6ff",
        "surface-container-highest": "#e4e2e2",
        "on-background": "#1b1c1c",
        "inverse-on-surface": "#f2f0f0",
        "surface-variant": "#e4e2e2",
        "surface-container": "#efeded",
        "on-primary-fixed": "#001a42",
        "secondary-container": "#75f8b3",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#007147",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-container": "#412e00",
        "tertiary-fixed": "#ffdfa0",
        "surface-container-low": "#f5f3f3",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        tertiary: "#271a00",
        "surface-dim": "#dbd9d9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        "ambient": "0 20px 40px rgba(0, 27, 68, 0.06)",
        "card": "0 4px 12px rgba(0, 27, 68, 0.03)",
      },
    },
  },
  plugins: [],
};
export default config;
